version: "3.8"

services:
  videat-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      videat-db:
        condition: service_healthy
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
      - FALLBACK_LANGUAGE=${FALLBACK_LANGUAGE}
      - APP_PORT=${APP_PORT}
    volumes:
      - /usr/src/app/node_modules

  videat-db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres_data:
